import { useEffect } from "react";
import { useNavigate } from "react-router-dom";
import { ArrowLeft } from "lucide-react";
import { Button } from "@/components/ui/button";
import Header from "@/components/Header";

const TermsOfService = () => {
  const navigate = useNavigate();

  useEffect(() => {
    window.scrollTo(0, 0);
  }, []);

  return (
    <div className="min-h-screen bg-background">
      <Header />
      <main className="container mx-auto px-4 py-8 max-w-4xl">
        <Button
          variant="ghost"
          onClick={() => navigate("/")}
          className="mb-6"
        >
          <ArrowLeft className="mr-2 h-4 w-4" />
          Back to Home
        </Button>

        <article className="prose prose-lg dark:prose-invert max-w-none">
          <header className="mb-8 border-b pb-6">
            <h1 className="text-4xl font-bold mb-4 text-foreground">
              ⚖️ Sarkari Khozo — Terms of Service
            </h1>
            <div className="text-sm text-muted-foreground">
              <p><strong>Effective Date:</strong> 24 October 2025</p>
            </div>
          </header>

          <section className="mb-8">
            <p className="text-lg text-foreground leading-relaxed">
              Please read these Terms carefully before using <strong>Sarkari Khozo</strong>.
              By accessing or using our platform, you agree to these Terms.
            </p>
          </section>

          <section className="mb-8">
            <h2 className="text-2xl font-semibold mb-4 text-foreground">1. About Sarkari Khozo</h2>
            <p className="text-foreground">
              Sarkari Khozo is an AI-powered platform that helps users discover, track, and understand government exams, schemes, policies, and jobs in India.
              We provide simplified summaries and alerts based on verified public data, but we are not an official government website.
            </p>
          </section>

          <section className="mb-8">
            <h2 className="text-2xl font-semibold mb-4 text-foreground">2. Use of the Platform</h2>
            <p className="text-foreground mb-4">You agree to use Sarkari Khozo:</p>
            <ul className="list-disc pl-6 space-y-2 text-foreground">
              <li>Only for lawful and personal informational purposes.</li>
              <li>Without misusing or attempting unauthorized access.</li>
              <li>Without scraping, replicating, or reselling our content.</li>
            </ul>
            <p className="text-foreground mt-4">
              We reserve the right to restrict or suspend access for misuse or violation of these Terms.
            </p>
          </section>

          <section className="mb-8">
            <h2 className="text-2xl font-semibold mb-4 text-foreground">3. Information Accuracy</h2>
            <p className="text-foreground mb-4">
              We make every effort to ensure that all exam, job, and scheme details are accurate and up to date.
              However, official notifications always take precedence.
              Users should verify critical details (like eligibility, dates, or forms) on respective official websites.
            </p>
            <p className="text-foreground font-semibold">
              We do not guarantee 100% accuracy, completeness, or timeliness of data.
            </p>
          </section>

          <section className="mb-8">
            <h2 className="text-2xl font-semibold mb-4 text-foreground">4. AI-Generated Content</h2>
            <p className="text-foreground mb-4">
              Some summaries, insights, or audio explanations are generated by AI (Claude, GPT, or other models).
              While we use quality filters and manual checks, AI-generated content may occasionally contain errors.
              Please use discretion and confirm through official sources before taking action.
            </p>
          </section>

          <section className="mb-8">
            <h2 className="text-2xl font-semibold mb-4 text-foreground">5. Notifications & Tracking</h2>
            <p className="text-foreground mb-4">When you use our "Track My Application" or "Reminders" features:</p>
            <ul className="list-disc pl-6 space-y-2 text-foreground">
              <li>You consent to receive alerts via the platform or email.</li>
              <li>You can opt-out anytime.</li>
              <li>Data used for tracking (like application name or ID) is stored securely and not shared with third parties.</li>
            </ul>
          </section>

          <section className="mb-8">
            <h2 className="text-2xl font-semibold mb-4 text-foreground">6. Intellectual Property</h2>
            <p className="text-foreground mb-4">
              All text, design, and technology on Sarkari Khozo are our property or licensed to us.
            </p>
            <p className="text-foreground mb-2">You may:</p>
            <ul className="list-disc pl-6 space-y-2 text-foreground mb-4">
              <li>Share links publicly (e.g., on social media).</li>
            </ul>
            <p className="text-foreground">
              But you may not copy, modify, or distribute content without permission.
            </p>
          </section>

          <section className="mb-8">
            <h2 className="text-2xl font-semibold mb-4 text-foreground">7. Third-Party Links</h2>
            <p className="text-foreground">
              Our platform may contain links to government or third-party websites.
              We are not responsible for their content, accuracy, or privacy practices.
            </p>
          </section>

          <section className="mb-8">
            <h2 className="text-2xl font-semibold mb-4 text-foreground">8. Disclaimer of Liability</h2>
            <p className="text-foreground mb-4">
              Sarkari Khozo is an informational service.
              We are not responsible for:
            </p>
            <ul className="list-disc pl-6 space-y-2 text-foreground">
              <li>Missed deadlines, losses, or rejections due to reliance on our summaries.</li>
              <li>Technical issues, downtime, or delays.</li>
              <li>Any financial or legal outcome resulting from use of our platform.</li>
            </ul>
            <p className="text-foreground mt-4 font-semibold">
              All use is at your own discretion.
            </p>
          </section>

          <section className="mb-8">
            <h2 className="text-2xl font-semibold mb-4 text-foreground">9. Limitation of Liability</h2>
            <p className="text-foreground">
              To the maximum extent permitted by law, Sarkari Khozo and its team shall not be liable for indirect, incidental, or consequential damages arising from your use of the platform.
            </p>
          </section>

          <section className="mb-8">
            <h2 className="text-2xl font-semibold mb-4 text-foreground">10. Account Termination</h2>
            <p className="text-foreground">
              If users abuse the service, attempt to manipulate data, or misuse AI summaries, we may suspend or delete their account (if applicable).
            </p>
          </section>

          <section className="mb-8">
            <h2 className="text-2xl font-semibold mb-4 text-foreground">11. Modifications</h2>
            <p className="text-foreground">
              We may revise these Terms from time to time.
              Continued use after updates means you accept the new Terms.
            </p>
          </section>

          <section className="mb-8">
            <h2 className="text-2xl font-semibold mb-4 text-foreground">12. Governing Law</h2>
            <p className="text-foreground">
              These Terms are governed by the laws of India.
              Disputes will fall under the jurisdiction of courts in New Delhi, India.
            </p>
          </section>

          <section className="mb-8">
            <h2 className="text-2xl font-semibold mb-4 text-foreground">13. Contact</h2>
            <p className="text-foreground mb-2">
              For legal or user-related queries:
            </p>
            <p className="text-foreground">
              📩 <a href="mailto:piyush@gradeai.in" className="text-primary hover:underline">piyush@gradeai.in</a>
            </p>
            <p className="text-foreground mt-2">
              🌐 <a href="https://www.sarkarikhozo.in" className="text-primary hover:underline">www.sarkarikhozo.in</a>
            </p>
          </section>
        </article>
      </main>

      <footer className="py-8 bg-transparent border-t">
        <div className="container mx-auto text-center space-y-2">
          <p className="text-sm text-foreground">
            © 2025 All rights reserved.
          </p>
          <p className="text-xs text-muted-foreground">
            Built with ❤️ by Piyush
          </p>
        </div>
      </footer>
    </div>
  );
};

export default TermsOfService;
